
package Visao;

import Controle.CLancamento;
import Controle.CObserver;
import Controle.CProduto;
import Controle.CVenda;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo H. G. Matsushita
 *
 */

public final class BuscaObs extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscaObs
     * @param codprod
     */
    public BuscaObs(String codprod, String data) {
        initComponents();
        txtcodigo.setText(codprod);
        txtdata.setText(data);
        Pesquisa();
        Tabela();
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        txtcodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtqntprod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        txtnome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtvenda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtverifica = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtdata = new javax.swing.JTextField();

        setTitle("Update");

        tabelaCliente.setBackground(new java.awt.Color(204, 204, 255));
        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código da Venda", "Código do Produto", "Quantidade"
            }
        ));
        tabelaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCliente);

        txtcodigo.setEditable(false);
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        jLabel5.setText("Código do Produto:");

        txtqntprod.setEditable(false);
        txtqntprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqntprodActionPerformed(evt);
            }
        });

        jLabel6.setText("Quantidade Disponível:");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Png 32 x 32/Exit.png"))); // NOI18N
        jButton6.setText("Sair");
        jButton6.setToolTipText("Sair");
        jButton6.setName("cmdSalvar"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txtnome.setEditable(false);
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome / Descrição: ");

        jLabel8.setText("Código da Venda:");

        txtvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvendaActionPerformed(evt);
            }
        });

        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Png 32 x 32/Accept.png"))); // NOI18N
        jButton4.setText("Concluir");
        jButton4.setName("cmdSalvar"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtverifica.setEditable(false);
        txtverifica.setForeground(new java.awt.Color(0, 153, 0));
        txtverifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtverificaActionPerformed(evt);
            }
        });

        jLabel1.setText("Data:");

        txtdata.setEditable(false);
        txtdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtvenda, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(txtverifica, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtqntprod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtqntprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(txtverifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(27, 27, 27))
        );

        setBounds(280, 50, 757, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaClienteMouseClicked

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtqntprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqntprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqntprodActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvendaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PesquisaConfere();
        //LimpaCampos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Conclui();
        LimpaCampos();
        Pesquisa();
        Tabela();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtverificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtverificaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtverificaActionPerformed

    private void txtdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdataActionPerformed
    private Vector pegaColunasDaGrade() {
        //Adicionar colunas na tabela
        Vector<String> ColunasTabela = new Vector<String>();
        ColunasTabela.add("Código da Venda");
        ColunasTabela.add("Código do Produto");
        ColunasTabela.add("Quantidade");
        
        return ColunasTabela;
    }
    public void Tabela(){
        ArrayList<String> Parametros = new ArrayList<String>();
        Parametros.add("0");
        Parametros.add(txtcodigo.getText().toUpperCase());//toUpperCase faz a mudança de maiuscula em minuscula
        
        //criando a estrutura da tabela
        Vector<String> vColunas = new Vector<String>();
        vColunas = pegaColunasDaGrade();//função que reotrnar quais são as colunas da tabela
        
        //modelo da tabela
        DefaultTableModel objTabela = new DefaultTableModel(vColunas,0);//passando quais sãoa as colunas e qntas linhas são
        
        //criando o controller da aplicação para efetuar a chamada da consulta
        CObserver CntrlObserver = new CObserver();
        objTabela = CntrlObserver.PesquisaObjeto(Parametros,objTabela);
        
        //atribuindo tabela ao JTable
        tabelaCliente.setModel(objTabela);
    }
    
    public void Pesquisa(){
        String CodPesquisa = txtcodigo.getText();
        int i = Integer.parseInt(CodPesquisa);
        CProduto CntroleProduto = new CProduto();
        ArrayList<String> Registro = new ArrayList<String>();
      
        Registro = CntroleProduto.Buscar(i);
        txtcodigo.setText(Registro.get(0));
        txtnome.setText(Registro.get(1));
        txtqntprod.setText(Registro.get(3));
    }
    
    public void PesquisaConfere(){
        String CodPesquisa = txtvenda.getText();
        int i = Integer.parseInt(CodPesquisa);
        CObserver CntroleObserver = new CObserver();
        ArrayList<String> Registro = new ArrayList<String>();
        Registro = CntroleObserver.Buscar(i);
        int ValorQnt = Integer.parseInt(Registro.get(3));
        int ValorEx = Integer.parseInt(txtqntprod.getText()); 
        if (ValorQnt > ValorEx){
            JOptionPane.showMessageDialog(null,"Esse pedido ainda não pode ser concluído!","ERRO!",JOptionPane.INFORMATION_MESSAGE);
        } else {
            txtverifica.setText("VERIFICADO!");
        }
    }
    
    public void Conclui(){
        if(txtverifica.getText() == null || txtverifica.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Verifique o código da venda!","Alerta",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(txtvenda.getText() == null || txtvenda.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Preencha o código da venda!","Alerta",JOptionPane.INFORMATION_MESSAGE);
            txtvenda.requestFocus();
            
       } else {
            String CodPesquisa = txtvenda.getText();
            int i = Integer.parseInt(CodPesquisa);
            CObserver CntroleObserver = new CObserver();
            ArrayList<String> Registro = new ArrayList<String>();
      
            Registro = CntroleObserver.Buscar(i);
            
            int ValorQnt = Integer.parseInt(Registro.get(3));
            int ValorEx = Integer.parseInt(txtqntprod.getText());
            
            ValorEx = ValorEx - ValorQnt;
            
            
            String CodPesquisa2 = txtcodigo.getText();
            int i2 = Integer.parseInt(CodPesquisa2);
            CProduto CntroleProduto = new CProduto();
            ArrayList<String> Registro2 = new ArrayList<String>();
      
            Registro2 = CntroleProduto.Buscar(i2);
                        
            ArrayList<String> Registro3 = new ArrayList<String>();
            Registro3.add(txtcodigo.getText());
            Registro3.add(txtnome.getText());
            Registro3.add(Registro2.get(2));
            Registro3.add(String.valueOf(ValorEx));
            Registro3.add(Registro2.get(4));
            Registro3.add(Registro2.get(5));
            CProduto cproduto = new CProduto();
            cproduto.Alterar(Registro3);
                        
            ArrayList<String> alancamento = new ArrayList<String>();
            alancamento.add("0");
            alancamento.add(txtcodigo.getText());
            alancamento.add(String.valueOf(ValorQnt));
            alancamento.add("Conclusão de Pedido");
            alancamento.add(txtdata.getText());
            CLancamento clancamento = new CLancamento();
            clancamento.Salvar(alancamento);
            
            CObserver cobs = new CObserver();
            cobs.Excluir(txtvenda.getText());
            
            CVenda cvenda = new CVenda();
            cvenda.Update(Integer.parseInt(txtvenda.getText()));
            
            JOptionPane.showMessageDialog(null,"Pedido Concluido!","Alerta",JOptionPane.INFORMATION_MESSAGE);
       
        }
    }

    public void LimpaCampos(){//seta tudo para limpar os campos
        int CodigoProduto = 0;
        txtvenda.setText(null);
        txtverifica.setText(null);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdata;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtqntprod;
    private javax.swing.JTextField txtvenda;
    private javax.swing.JTextField txtverifica;
    // End of variables declaration//GEN-END:variables

    public void setPosicao() {  
        Dimension d = this.getDesktopPane().getSize();  
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }    

  

}
