package Visao;

import static Visao.VPrincipal.jDesktopPane;
import javax.swing.JOptionPane;

import Controle.CLancamento;
import Controle.CProduto;
import Modelo.Lancamentos;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.util.ArrayList;


/**
 *
 * @author Gustavo H. G. Matsushita
 *
 */

public class JVGLancamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form JVGLancamento
     */
    public JVGLancamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtqntprod = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtobs = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtdata = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cbmTipo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtQnt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUni = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cbmStatus = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gerenciar Lançamentos");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Png 32 x 32/Delete.png"))); // NOI18N
        jButton7.setText("Limpar");
        jButton7.setToolTipText("Limpar Campos");
        jButton7.setName("cmdSalvar"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Png 32 x 32/Exit.png"))); // NOI18N
        jButton6.setText("Sair");
        jButton6.setToolTipText("Sair");
        jButton6.setName("cmdSalvar"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("* Campos obrigatórios ");

        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("*");

        jLabel15.setText("Quantidade:");

        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("*");

        jLabel16.setText("Observação:");

        try {
            txtdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel17.setText("Data:");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Png 32 x 32/Accept.png"))); // NOI18N
        jButton4.setText("Confirmar");
        jButton4.setName("cmdSalvar"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel18.setText("Tipo de Lançamento: ");

        cbmTipo.setBackground(new java.awt.Color(230, 230, 230));
        cbmTipo.setEditable(true);
        cbmTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Saida", "Incidente", "Entrada" }));
        cbmTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmTipoActionPerformed(evt);
            }
        });

        jLabel5.setText("Código do Produto:");

        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("*");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Png 32 x 32/viewmag.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Png 32 x 32/Line Chart.png"))); // NOI18N
        jButton2.setText("Lista de Produtos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setText("*");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setText("Nome / Descrição: ");

        txtnome.setEditable(false);
        txtnome.setBackground(new java.awt.Color(230, 230, 230));

        txtQnt.setEditable(false);
        txtQnt.setBackground(new java.awt.Color(230, 230, 230));
        txtQnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQntActionPerformed(evt);
            }
        });

        jLabel2.setText("Preço:");

        jLabel1.setText("Quantidade em Estoque:");

        jLabel8.setText("reais");

        txtPreco.setEditable(false);
        txtPreco.setBackground(new java.awt.Color(230, 230, 230));

        jLabel3.setText("gramas");

        jLabel7.setText("Unidade de Medida:");

        txtUni.setEditable(false);
        txtUni.setBackground(new java.awt.Color(230, 230, 230));

        jLabel19.setText("Status:");

        cbmStatus.setBackground(new java.awt.Color(230, 230, 230));
        cbmStatus.setEditable(true);
        cbmStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));
        cbmStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUni)
                                    .addComponent(txtQnt, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbmStatus, 0, 103, Short.MAX_VALUE)
                                    .addComponent(txtPreco))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtobs, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtqntprod)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(202, 202, 202))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(cbmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18)
                    .addComponent(cbmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtqntprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(txtobs, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(jButton2)
                    .addComponent(jLabel14)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        setBounds(350, 50, 654, 618);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        LimpaCampos();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        ArrayList<String> Registro = new ArrayList<String>();
        ArrayList<String> Atualiza = new ArrayList<String>();

        if (validaCampos() == true){ //Verifica os campos obrigatorios
            if (validaQnt() == true){ //Valida a quantidade inserida e compara com a qnt do Produto
                //Gera o lançamento
                Registro.add(String.valueOf(cbmTipo.getSelectedIndex()));
                Registro.add(txtcodigo.getText());
                Registro.add(txtqntprod.getText());
                Registro.add(txtobs.getText());
                Registro.add(txtdata.getText());
                CLancamento clancamento = new CLancamento();
                clancamento.Salvar(Registro);
                
                int entrada = (Integer.parseInt(txtqntprod.getText()));
                int saida = (Integer.parseInt(txtQnt.getText()));
                if ((cbmTipo.getSelectedIndex()) == 0 || (cbmTipo.getSelectedIndex()) == 1){
                    saida = (saida - entrada);
                } else {
                   saida = (saida + entrada); 
                }
                
                Atualiza.add(txtcodigo.getText());
                Atualiza.add(txtnome.getText());
                Atualiza.add(txtUni.getText());
                Atualiza.add(String.valueOf(saida));
                Atualiza.add(txtPreco.getText());
                Atualiza.add(String.valueOf(cbmStatus.getSelectedIndex()));

                CProduto cproduto = new CProduto();
                cproduto.Alterar(Atualiza);
                
                
                JOptionPane.showMessageDialog(null,"Lançamento feito com sucesso !","Lançamento",JOptionPane.INFORMATION_MESSAGE);
                LimpaCampos();
            }
            
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cbmTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmTipoActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String CodPesquisa = txtcodigo.getText();
        int i = Integer.parseInt(CodPesquisa);
        Pesquisa(i);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        BuscaProduto frmDist = new BuscaProduto();
        jDesktopPane.add(frmDist);
        frmDist.setVisible(true);
        frmDist.setPosicao();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtQntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQntActionPerformed

    }//GEN-LAST:event_txtQntActionPerformed

    private void cbmStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmStatusActionPerformed
    public void Pesquisa(int i){
        
        CProduto CntroleProduto = new CProduto();
        ArrayList<String> Registro = new ArrayList<String>();
      
        Registro = CntroleProduto.Buscar(i);
        txtcodigo.setText(Registro.get(0));
        txtnome.setText(Registro.get(1));
        txtUni.setText(Registro.get(2));
        txtQnt.setText(Registro.get(3));
        txtPreco.setText(Registro.get(4));
        cbmStatus.setSelectedIndex(Integer.parseInt(Registro.get(5)));
    }
    
    public void LimpaCampos(){//seta tudo para limpar os campos
        int CodigoProduto = 0;
        txtcodigo.setText(null);
        txtnome.setText(null);
        txtUni.setText(null);
        txtQnt.setText(null);
        txtPreco.setText(null);
        txtqntprod.setText(null);
        txtdata.setText(null);
        txtobs.setText(null);
    }
    
    public boolean validaQnt(){
        boolean ret = false;
        int entrada = (Integer.parseInt(txtqntprod.getText()));
        if (entrada > 0){
            if ((cbmTipo.getSelectedIndex()) == 0 || (cbmTipo.getSelectedIndex()) == 1){
                int saida = (Integer.parseInt(txtQnt.getText()));
                saida = (saida - entrada);
                if (saida >= 0){
                    ret = true;
                } else {
                   JOptionPane.showMessageDialog(null,"Quantidade invalida!","Alerta",JOptionPane.INFORMATION_MESSAGE);
                   txtqntprod.requestFocus(); 
                }
            } else {
                ret = true;
            }
            
        } else {
            JOptionPane.showMessageDialog(null,"Quantidade invalida!","Alerta",JOptionPane.INFORMATION_MESSAGE);
            txtqntprod.requestFocus();
        }
        return ret;
    }

    public boolean validaCampos() {
        boolean ret = true;
        if (txtdata.getText().equals("  /  /    ") || txtdata.getText() == null){
            JOptionPane.showMessageDialog(null,"Preencha o campo Data!","Alerta",JOptionPane.INFORMATION_MESSAGE);
            txtdata.requestFocus();
            ret=false;
        }else if(txtqntprod.getText() == null || txtqntprod.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Preencha o campo Quantidade!","Alerta",JOptionPane.INFORMATION_MESSAGE);
            txtqntprod.requestFocus();
            ret=false;
        }
        else if(txtcodigo.getText() == null || txtcodigo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Preencha o campo Código!","Alerta",JOptionPane.INFORMATION_MESSAGE);
            txtcodigo.requestFocus();
            ret=false;
       }
       else if(txtnome.getText() == null || txtnome.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Valide o código do produto!","Alerta",JOptionPane.INFORMATION_MESSAGE);
            txtcodigo.requestFocus();
            ret=false;
       }
       else if((cbmStatus.getSelectedIndex()) == 1) {
            JOptionPane.showMessageDialog(null,"PRODUTO INATIVO! Altere o status do produto","Alerta",JOptionPane.INFORMATION_MESSAGE);
            txtcodigo.requestFocus();
            ret=false;
       }
       
        return ret;
    }

    public boolean validaCamposTeste(String campodata, String campoqnt, String campocod, String campoverifica, int status) {
        boolean ret = true;
        if (campodata.equals("  /  /    ") || campodata.equals("")){
            JOptionPane.showMessageDialog(null,"Preencha o campo Data!","Alerta",JOptionPane.INFORMATION_MESSAGE);
            //txtdata.requestFocus();
            ret=false;
        }else if(campoqnt == null || campoqnt.equals("")){
            JOptionPane.showMessageDialog(null,"Preencha o campo Quantidade!","Alerta",JOptionPane.INFORMATION_MESSAGE);
            //txtqntprod.requestFocus();
            ret=false;
        }
        else if(campocod == null || campocod.equals("")){
            JOptionPane.showMessageDialog(null,"Preencha o campo Código do produto!","Alerta",JOptionPane.INFORMATION_MESSAGE);
            //txtcodigo.requestFocus();
            ret=false;
       }
       else if(campoverifica == null || campoverifica.equals("")){
            JOptionPane.showMessageDialog(null,"Valide o código do produto!","Alerta",JOptionPane.INFORMATION_MESSAGE);
            //txtcodigo.requestFocus();
            ret=false;
       }
       else if(status == 1) {
            JOptionPane.showMessageDialog(null,"PRODUTO INATIVO! Altere o status do produto","Alerta",JOptionPane.INFORMATION_MESSAGE);
            //txtcodigo.requestFocus();
            ret=false;
       }
       
        return ret;
    }
    
    public boolean validaQntTeste(int tipo, int qntlan, int qntprod){
        boolean ret = false;
        int entrada = qntlan;
        if (entrada > 0){
            if (tipo == 0 || tipo == 1){
                int saida = (qntprod);
                saida = (saida - entrada);
                if (saida >= 0){
                    ret = true;
                } else {
                   JOptionPane.showMessageDialog(null,"Quantidade invalida!","Alerta",JOptionPane.INFORMATION_MESSAGE);
                   //txtqntprod.requestFocus(); 
                }
            } else {
                ret = true;
            }
            
        } else {
            JOptionPane.showMessageDialog(null,"Quantidade invalida!","Alerta",JOptionPane.INFORMATION_MESSAGE);
            //txtqntprod.requestFocus();
        }
        return ret;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbmStatus;
    private javax.swing.JComboBox cbmTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQnt;
    private javax.swing.JTextField txtUni;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JFormattedTextField txtdata;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtobs;
    private javax.swing.JTextField txtqntprod;
    // End of variables declaration//GEN-END:variables

    public void setPosicao() {  
        Dimension d = this.getDesktopPane().getSize();  
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }   
}
